### ISSUE TITLE
error when trying to dump the model into tmp file

### ISSUE THREAD

**Issue by bensdm** [text-machine-lab/CliNER#10]
Hi, thanks for this beautiful project. I am trying to run this code but have an issue: no such file or directory "/tmp\\tmp20_08sb3crf_temp" when executing crf.py, line 176, in predict:
os_handle,tmp_file = tempfile.mkstemp(dir='/tmp', suffix="crf_temp")

thanks for your help

**Comment by wboag** [comment]
I notice that the mkstemp makes the path "/tmp\tmp20_08sb3crf_temp" with a \ path delimiter, which means I hadn't wrote that with windows in mind.

I just made a change to the code to use data/tmp (or data\tmp for windows) instead of assuming the system has a /tmp directory. It should work now. Let me know if there are any path issues from running it now (it's possible I added one too many dirname calls somewhere, though I think I got them right).

If that filepath issue resolves, let me know and I'll close this thread :)

**Comment by bensdm** [comment]
thanks for your quick reponse, there is just a syntax error line 436 of model.py:
parameters['conll_like_result_folder']=eval_dir)
but once the ")" deleted i have a new issue line 181 of crf.py:
f.write(clf)  -> a bytes like object is required, not str
i tried to change the wb to w and w+ but new error of encoding....
i also tried f.write(clf.encode()) but python is now crashing ...
any idea?

**Comment by dsouzadaniel** [comment]
I think I have the fix :) Can I create a PR @wboag ?

**Update** : Fixed the issue. Let me know if it works @bensdm 😄

**Comment by bensdm** [comment]
It does thanks but the ")" is still there line 436 ;)

**Comment by jmoseyko** [comment]
Am unfortunately still experiencing the issue after removing the ")" in model.py, with error "UnicodeDecodeError: 'ascii' codec can't decode byte 0x85 in position 5: ordinal not in range(128)" from line 181 in crf.py

Update: issue resolved when line 181 in crf.py is changed back to "f.write(clf)" instead of new commit "clf_byte = bytearray(clf, 'latin1')
 f.write(clf_byte)"
